# Generated by Django 2.2.12 on 2020-04-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=4)),
                ('mobile_code', models.CharField(blank=True, max_length=2)),
                ('iata', models.CharField(max_length=2)),
                ('trunk_prefix', models.CharField(blank=True, default='0', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NumGeoAr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=20)),
                ('modalidad', models.CharField(max_length=20)),
                ('localidad', models.CharField(max_length=50)),
                ('indicativo', models.CharField(db_index=True, max_length=10)),
                ('bloque', models.CharField(db_index=True, max_length=5)),
                ('resolucion', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizer.Country')),
            ],
        ),
        migrations.CreateModel(
            name='NumGeoMx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_censal', models.CharField(max_length=20)),
                ('poblacion', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=10)),
                ('presuscripcion', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=10)),
                ('asl', models.CharField(max_length=10)),
                ('nir', models.CharField(db_index=True, max_length=10)),
                ('serie', models.CharField(db_index=True, max_length=10)),
                ('numeracion_inicial', models.CharField(db_index=True, max_length=10)),
                ('numeracion_final', models.CharField(db_index=True, max_length=10)),
                ('ocupacion', models.CharField(max_length=10)),
                ('tipo_red', models.CharField(max_length=20)),
                ('modalidad', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=100)),
                ('fecha_asignacion', models.CharField(max_length=10)),
                ('fecha_consolidacion', models.CharField(max_length=10)),
                ('fecha_migracion', models.CharField(max_length=10)),
                ('nir_anterior', models.CharField(max_length=10)),
            ],
        ),
    ]
